export const CURRENCY_OPTIONS: { code: string; label: string }[] = [
    { code: 'USD', label: 'USD — US Dollar' },
    { code: 'LKR', label: 'LKR — Sri Lankan Rupee' },
    { code: 'INR', label: 'INR — Indian Rupee' },
    { code: 'GBP', label: 'GBP — British Pound' },
    { code: 'EUR', label: 'EUR — Euro' },
    { code: 'AUD', label: 'AUD — Australian Dollar' },
    { code: 'CAD', label: 'CAD — Canadian Dollar' },
    { code: 'AED', label: 'AED — UAE Dirham' },
    { code: 'SGD', label: 'SGD — Singapore Dollar' },
    { code: 'MYR', label: 'MYR — Malaysian Ringgit' },
    { code: 'NZD', label: 'NZD — New Zealand Dollar' },
    { code: 'ZAR', label: 'ZAR — South African Rand' },
    { code: 'JPY', label: 'JPY — Japanese Yen' },
    { code: 'CNY', label: 'CNY — Chinese Yuan' },
    { code: 'PKR', label: 'PKR — Pakistani Rupee' },
    { code: 'BDT', label: 'BDT — Bangladeshi Taka' },
    { code: 'NPR', label: 'NPR — Nepalese Rupee' },
    { code: 'SAR', label: 'SAR — Saudi Riyal' },
    { code: 'QAR', label: 'QAR — Qatari Riyal' },
    { code: 'THB', label: 'THB — Thai Baht' },
];
