import type { ReportDefinition } from './types';

export const reportDefinitions: ReportDefinition[] = [
    {
        key: 'membership-summary',
        title: 'Membership Summary',
        description: 'Membership totals and status mix.',
        category: 'Membership',
        permission: 'reports.membership.view',
        filters: ['date_range', 'branch', 'plan', 'member_status'],
    },
    {
        key: 'membership-sales',
        title: 'Membership Sales',
        description: 'New memberships sold over time.',
        category: 'Membership',
        permission: 'reports.membership.view',
        filters: ['date_range', 'branch', 'plan'],
    },
    {
        key: 'renewals',
        title: 'Renewals',
        description: 'Renewal volume and conversion.',
        category: 'Membership',
        permission: 'reports.membership.view',
        filters: ['date_range', 'branch', 'plan'],
    },
    {
        key: 'expiries',
        title: 'Expiries',
        description: 'Upcoming and completed membership expiries.',
        category: 'Membership',
        permission: 'reports.membership.view',
        filters: ['date_range', 'branch', 'plan'],
    },
    {
        key: 'daily-attendance',
        title: 'Daily Attendance',
        description: 'Daily check-in and check-out activity.',
        category: 'Attendance',
        permission: 'reports.attendance.view',
        filters: ['date_range', 'branch'],
    },
    {
        key: 'peak-hours',
        title: 'Peak Hours',
        description: 'Busiest periods across branches.',
        category: 'Attendance',
        permission: 'reports.attendance.view',
        filters: ['date_range', 'branch'],
    },
    {
        key: 'member-frequency',
        title: 'Member Frequency',
        description: 'Visit frequency and engagement segments.',
        category: 'Attendance',
        permission: 'reports.attendance.view',
        filters: ['date_range', 'branch'],
    },
    {
        key: 'sales',
        title: 'Sales',
        description: 'Invoiced sales and net totals.',
        category: 'Financial',
        permission: 'reports.financial.view',
        filters: ['date_range', 'branch', 'payment_method'],
    },
    {
        key: 'collections',
        title: 'Collections',
        description: 'Payments collected by method and branch.',
        category: 'Financial',
        permission: 'reports.financial.view',
        filters: ['date_range', 'branch', 'payment_method'],
    },
    {
        key: 'outstanding-balances',
        title: 'Outstanding Balances',
        description: 'Open member balances and ageing.',
        category: 'Financial',
        permission: 'reports.financial.view',
        filters: ['date_range', 'branch'],
    },
    {
        key: 'refunds',
        title: 'Refunds',
        description: 'Refunded payments and reasons.',
        category: 'Financial',
        permission: 'reports.financial.view',
        filters: ['date_range', 'branch', 'payment_method'],
    },
    {
        key: 'staff-activity',
        title: 'Staff Activity',
        description: 'High-value operational actions by staff.',
        category: 'Operations',
        permission: 'reports.staff-activity.view',
        filters: ['date_range', 'branch'],
    },
    {
        key: 'notification-delivery',
        title: 'Notification Delivery',
        description: 'Delivery, retry and failure performance.',
        category: 'Operations',
        permission: 'reports.notification-delivery.view',
        filters: ['date_range', 'branch'],
    },
    {
        key: 'branch-performance',
        title: 'Branch Performance',
        description: 'Membership, attendance and financial comparison.',
        category: 'Operations',
        permission: 'reports.branch-performance.view',
        filters: ['date_range', 'branch'],
    },
];
